version: '3'

services:  
  epltrc-ui:
    image: niq77avie/dynamiko-ui
    container_name: "EPLTRC_UI"
    volumes:
      - /etc/letsencrypt/live/dynamikosoft.com:/etc/nginx/certs
    ports:
      - "7001:443"

  epltrc-service:
    image: niq77avie/dynamiko-python-service
    container_name: "EPLTRC_Service"
    volumes:
      - /etc/letsencrypt/live/dynamikosoft.com:/app/certs
    ports:
      - "8001:8888"
    environment:
      - DYNAMIKO_DOMAIN=dynamikosoft.com
      - MYSQL_URL=mysql+pymysql://epltrc:epltrc@dynamikosoft.com:3306/epltrc

volumes:
  portainer_data: