version: '3'

services:
  dynamiko-ui:
    image: niq77avie/dynamiko-ui
    container_name: "Dynamiko_UI"
    volumes:
      - C:/Work/innovation/dynamiko/ui/dynamiko-ui:/usr/share/nginx/html
    ports:
      - "7777:7777"
