version: '3'

services:
  dynamiko-ui:
    image: niq77avie/dynamiko-ui
    container_name: "Dynamiko_UI"
    volumes:
      - /home/alex/innovation/dynamiko/ui/dynamiko-ui:/usr/share/nginx/html
    ports:
      - "7777:7777"

  dynamiko-service:
    image: niq77avie/dynamiko-python-service
    container_name: "Dynamiko_Service"
    volumes:
      - /home/alex/innovation/dynamiko/server/dynamiko-python-service:/app
    ports:
      - "8888:8888"
    environment:
      - MYSQL_URL=mysql+pymysql://dynamikodb:dynamikodb@dynamikosoft.com:3306/dynamikodb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-wordpress
    environment:
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_PASSWORD_FILE: /run/secrets/dynamikodb.txt
    volumes:
      - /root/setup/phpmyadmin:/run/secrets
    restart: always
    ports:
      - 8080:80      
          
  # dynamiko-coturn:
  #   image: instrumentisto/coturn
  #   container_name: "Dynamiko_Coturn"
  #   ports:
  #     - "3478:3478"
  #     - "49152-65535:49152-65535/udp"

volumes:
  portainer_data: