version: '3'

services:
  mysql:
    image: mysql:8.0.21
    container_name: "MySQL"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Miran!11
  
  dynamiko-ui:
    image: niq77avie/dynamiko-ui
    container_name: "Dynamiko_UI"
    volumes:
      - /home/alex/innovation/dynamiko/ui/dynamiko-ui:/usr/share/nginx/html
    ports:
      - "7777:80"

  dynamiko-service:
    image: niq77avie/dynamiko-python-service
    container_name: "Dynamiko_Service"
    volumes:
      - /home/alex/innovation/dynamiko/server/dynamiko-python-service:/app
    ports:
      - "8888:8888"
    environment:
      - DYNAMIKO_DOMAIN=dynamikosoft.com
      - MYSQL_URL=mysql+pymysql://dynamikodb:dynamikodb@dynamikosoft.com:3306/dynamikodb

volumes:
  portainer_data: