version: '3'

services:
  dynamiko-ui:
    image: niq77avie/dynamiko-ui
    container_name: "Dynamiko_UI"
    volumes:
      - /home/alex/innovation/dynamiko/ui/dynamiko-ui:/usr/share/nginx/html
      - /etc/letsencrypt/live/dynamikosoft.com:/etc/nginx/certs
    ports:
      - "7777:7777"

  dynamiko-service:
    image: niq77avie/dynamiko-python-service
    container_name: "Dynamiko_Service"
    volumes:
      - /home/alex/innovation/dynamiko/server/dynamiko-python-service:/app
      - /etc/letsencrypt/live/dynamikosoft.com:/app/certs
    ports:
      - "8888:8888"
    environment:
      - DYNAMIKO_DOMAIN=|subdomain|dynamikosoft.com
      - MYSQL_URL=mysql+pymysql://dynamikodb:dynamikodb@|subdomain|dynamikosoft.com:3306/dynamikodb

volumes:
  portainer_data: