version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$DATABASE
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - MONGO_PORT=$DATABASE_PORT
    volumes:
      - /root/tmp/mongo/db:/data/db
      - /root/setup/19-mongodb/:/docker-entrypoint-initdb.d
    ports:
    - 27017:27017
