version: '3'

services:
  mongoschool:
    image: bitnami/mongodb
    container_name: "MongoSchool"
    ports:
      - "27701:27017"
    environment:
      - MONGODB_USERNAME=dynamiko
      - MONGODB_PASSWORD=dynamiko
      - MONGODB_DATABASE=dynamiko
    volumes:
      - /home/alex/innovation/mongodata/school:/bitnami/mongodb

  mongolawfirm:
    image: bitnami/mongodb
    container_name: "MongoLawFirm"
    ports:
      - "27702:27017"
    environment:
      - MONGODB_USERNAME=dynamiko
      - MONGODB_PASSWORD=dynamiko
      - MONGODB_DATABASE=dynamiko
    volumes:
      - /home/alex/innovation/mongodata/lawfirm:/bitnami/mongodb
        