version: '3'

services:
  mongodb:
    image: bitnami/mongodb
    container_name: "MongoDB"
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - MONGODB_USERNAME=dynamiko
      - MONGODB_PASSWORD=dynamiko
      - MONGODB_DATABASE=dynamiko
    volumes:
      - /home/alex/innovation/mongodata:/bitnami/mongodb
        