mongo:
  image: mongo
  restart: unless-stopped
  environment:
    MONGO_INITDB_ROOT_USERNAME: dynamiko
    MONGO_INITDB_ROOT_PASSWORD: dynamiko

mongo-express:
  image: mongo-express
  ports:
    - 8081:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: dynamiko
    ME_CONFIG_MONGODB_ADMINPASSWORD: dynamiko